version: '3.3'

services:
   db:
     image: yopiya/mysqlpj93v2
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - '7777:80'
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: somewordpress
        
   wordpress:
     depends_on:
       - db
     image: yopiya/wppj93v2
     ports:
       - "7000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     volumes:
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini  
    
   nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./default:/etc/nginx/conf.d
            
volumes:
    db_data: {}
